version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test

      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm test
  hellothere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "hellllooooo!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hellothere
      - test:
          requires:
            - hellothere

